version: "3.9"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: superadmin
      POSTGRES_DB: habbit-rabbit-db
      PGPORT: 5432
    expose:
      - 5432
  web:
    depends_on:
      - db
    image: rabbit-backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_TITLE: habbit-rabbit-db
      DB_PASSWORD: 123123
    ports:
      - 8080:8080
    restart: always